sudo: false
node_js:
- 6
install:
- gem install sass
- mkdir -p src/styles/css
- npm install -g codecov
- npm install
cache:
  directories:
  - node_modules
script:
- npm run sass:build
- npm test -- --coverage
- npm run build
after_success:
- codecov
deploy:
  provider: heroku
  api_key:
    secure: OwULt1xmjBW1wlknDdyG7jA1/CeMtzM6HwV3REoj+ccI0gx81rTToEFCrgF2JMQkUbFp/okGhvtarwm/ldJw53oFWIcOiF8d1OjAX7KWZTunN0mk29o1/9uKpAqf7S77IjDmUmOD6qLlAnkwzT/pTmI5AePK/a8cpwnpBspq1jpi0BmoLydqBf6O2h55kAu6GMEhtAdxQTNeyh3G2howNqCAONOvePAcE9EBZ7pMMXyWUgApQgWv4uFTRwElWc4mc2pNNfeDheBgTvjSPEOWKskXyWdAkHd04W9SvKFAkWaEKSCL1K7IVZFlw/skYAb5vYnCL8xRAaOMZOc7wE2iy2D1EftXXpd456FAO03jci/fRrWKhEiWrr9YaE0MT2emH9xx1S8eX73MiU359F5C8ZU1tDoH5vlRrhMDF+jTR+gKOIaMOEFtfbRPI2wL1T+B4hPRdomLKr7+4me8duJAMyRXH5BPNgwck7snw0Cpy1amo1NPtRmktzK0VCHbFkYMRoIwDdozzkvPrewYKcg0kdKpavkFbdgEoI0D4fCzy+7YUyOw8joZrZhFHbeZ9yvQWxU7j8hFehq9q5pZBKeYXIIERwGUZ2i0BsZOPQ3wMSQkymttEkvUVcDTE6gWVitRN9+OSHUrxDw5ri4vtOFmGKXJxnB+f5rpF9kADsErZ/I=
  app: quokka-prod
  skip_cleanup: true
  on:
    repo: quokkateam/quokka
